export const APPWRITE_ENV_KEYS = [
  "NEXT_PUBLIC_APPWRITE_ENDPOINT",
  "NEXT_PUBLIC_APPWRITE_PROJECT_ID",
  "NEXT_PUBLIC_APPWRITE_DATABASE_ID",
  "NEXT_PUBLIC_APPWRITE_MANGAS_COLLECTION_ID",
  "NEXT_PUBLIC_APPWRITE_CHAPTERS_COLLECTION_ID",
  "NEXT_PUBLIC_APPWRITE_CHAPTER_PAGES_COLLECTION_ID",
  "NEXT_PUBLIC_APPWRITE_USERS_COLLECTION_ID",
  "NEXT_PUBLIC_APPWRITE_COVERS_BUCKET_ID",
  "NEXT_PUBLIC_APPWRITE_PAGES_BUCKET_ID",
  "NEXT_PUBLIC_APPWRITE_AVATARS_BUCKET_ID",
] as const;

export type AppwriteEnvKey = (typeof APPWRITE_ENV_KEYS)[number];

export const NEXT_PUBLIC_APPWRITE_ENDPOINT =
  process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT ?? "";
export const NEXT_PUBLIC_APPWRITE_PROJECT_ID =
  process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID ?? "";
export const NEXT_PUBLIC_APPWRITE_DATABASE_ID =
  process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID ?? "";
export const NEXT_PUBLIC_APPWRITE_MANGAS_COLLECTION_ID =
  process.env.NEXT_PUBLIC_APPWRITE_MANGAS_COLLECTION_ID ?? "";
export const NEXT_PUBLIC_APPWRITE_CHAPTERS_COLLECTION_ID =
  process.env.NEXT_PUBLIC_APPWRITE_CHAPTERS_COLLECTION_ID ?? "";
export const NEXT_PUBLIC_APPWRITE_CHAPTER_PAGES_COLLECTION_ID =
  process.env.NEXT_PUBLIC_APPWRITE_CHAPTER_PAGES_COLLECTION_ID ?? "";
export const NEXT_PUBLIC_APPWRITE_USERS_COLLECTION_ID =
  process.env.NEXT_PUBLIC_APPWRITE_USERS_COLLECTION_ID ?? "";
export const NEXT_PUBLIC_APPWRITE_COVERS_BUCKET_ID =
  process.env.NEXT_PUBLIC_APPWRITE_COVERS_BUCKET_ID ?? "";
export const NEXT_PUBLIC_APPWRITE_PAGES_BUCKET_ID =
  process.env.NEXT_PUBLIC_APPWRITE_PAGES_BUCKET_ID ?? "";
export const NEXT_PUBLIC_APPWRITE_AVATARS_BUCKET_ID =
  process.env.NEXT_PUBLIC_APPWRITE_AVATARS_BUCKET_ID ?? "";

export const APPWRITE_ENV_VALUES: Record<AppwriteEnvKey, string> = {
  NEXT_PUBLIC_APPWRITE_ENDPOINT,
  NEXT_PUBLIC_APPWRITE_PROJECT_ID,
  NEXT_PUBLIC_APPWRITE_DATABASE_ID,
  NEXT_PUBLIC_APPWRITE_MANGAS_COLLECTION_ID,
  NEXT_PUBLIC_APPWRITE_CHAPTERS_COLLECTION_ID,
  NEXT_PUBLIC_APPWRITE_CHAPTER_PAGES_COLLECTION_ID,
  NEXT_PUBLIC_APPWRITE_USERS_COLLECTION_ID,
  NEXT_PUBLIC_APPWRITE_COVERS_BUCKET_ID,
  NEXT_PUBLIC_APPWRITE_PAGES_BUCKET_ID,
  NEXT_PUBLIC_APPWRITE_AVATARS_BUCKET_ID,
};

export const APPWRITE_DATABASE_ID = NEXT_PUBLIC_APPWRITE_DATABASE_ID;

export const APPWRITE_COLLECTIONS = {
  mangas: NEXT_PUBLIC_APPWRITE_MANGAS_COLLECTION_ID,
  chapters: NEXT_PUBLIC_APPWRITE_CHAPTERS_COLLECTION_ID,
  chapterPages: NEXT_PUBLIC_APPWRITE_CHAPTER_PAGES_COLLECTION_ID,
  users: NEXT_PUBLIC_APPWRITE_USERS_COLLECTION_ID,
} as const;

export const APPWRITE_BUCKETS = {
  covers: NEXT_PUBLIC_APPWRITE_COVERS_BUCKET_ID,
  pages: NEXT_PUBLIC_APPWRITE_PAGES_BUCKET_ID,
  avatars: NEXT_PUBLIC_APPWRITE_AVATARS_BUCKET_ID,
} as const;
